name: Android Feature Branch CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install npm deps
      run: npm install
    - name: Clean
      run: ./gradlew clean --stacktrace
    - name: Build debug
      run: ./gradlew assembleDebug --stacktrace
    - name: Unit tests
      run: ./gradlew testDebugUnitTest --stacktrace